project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('units/', include('units.urls' , namespace='units')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'AIRBNB Clone'
admin.site.site_title = 'AIRBNB Clone'

units/urls.py
from django.urls import path
from .views import all_units, single_unit, new_unit, unit_edit, unit_delete, unit_list, unit_update, unit_detail



app_name='units'

urlpatterns = [
    path('' , all_units , name='all_units_list'),
    path('new/' , new_unit , name='new_unit'),
    path('<str:slug>',single_unit,name='unit_detail'),
    path('<str:slug>/edit',unit_edit,name='unit_edit'),
    path('<str:slug>/delete',unit_delete,name='unit_delete'),

    #class based views
    path('cbv/<str:slug>',unit_detail.as_view(), name='cbv_detail'),
    path('cbv/new',unit_update.as_view()),
    path('cbv/<str:slug>/edit',unit_update.as_view()),
    path('cbv/',unit_list.as_view()),
]

units/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

UNIT_TYPE = (
    ('CHALEH','CHALEH'),
    ('ROOM' , 'ROOM'),
    ('FLAT' , 'FLAT'),
    ('STUDIO' , 'STUDIO'),
)

class Area(models.Model):
    title = models.CharField(max_length=60, verbose_name='Area', )

    def __str__(self):
        return self.title

class City(models.Model):
    title = models.CharField(max_length=60, verbose_name='City', )
    #area = models.ManyToManyField(Area)

    def __str__(self):
        return self.title

class Country(models.Model):
    title = models.CharField(max_length=60, verbose_name='Country', )
    #city = models.ManyToManyField(City)

    def __str__(self):
        return self.title

class Amenity(models.Model):
    title = models.CharField(max_length=60, verbose_name='Amenity', )

    def __str__(self):
        return self.title


class Unit(models.Model):

    title = models.CharField(max_length=60, verbose_name='Unit Title', )
    description = models.TextField(max_length=500, verbose_name='Unit Description')
    price = models.DecimalField(max_digits=10,decimal_places=2)
    num_bedrooms = models.IntegerField( verbose_name='Number of Bed rooms')
    image = models.ImageField(upload_to='units_images/' , blank=True , null=True, verbose_name='Unit Main Image')
    created = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)
    owner_email = models.EmailField(default='fahdkuwait@gmail.com')
    type = models.CharField(choices=UNIT_TYPE , default='ROOM',max_length=20)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    amenities = models.ManyToManyField(Amenity)
    slug = models.SlugField(null=False, unique=True)


    class Meta:
        verbose_name = 'Unit'
        verbose_name_plural = 'Units'
        ordering = ('-active',)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('units:unit_detail', kwargs={'slug': self.slug})


class Images(models.Model):
    unit =  models.ForeignKey(Unit,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='units_images/')

    def __str__(self):
        return self.title

class Comments(models.Model):
    author =  models.ForeignKey(User, related_name='comment_user', on_delete=models.CASCADE, null=True)
    unit = models.ForeignKey(Unit , on_delete=models.CASCADE, null=True)
    # post = models.ManyToManyField(Post)
    text = models.TextField(max_length=200)


    def __str__(self):
        return str(self.unit)

units/forms.py
from django import forms

from .models import Unit, Comments


class UnitForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text',]

units/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Unit, Comments
from django.urls import reverse
from .forms import UnitForm, CommentForm
from django.views.generic import ListView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

def all_units(request):
    ## logic
    all_units = Unit.objects.all()
    return render(request,'units/all_units.html' ,{'units':all_units})


def single_unit(request,slug):
    #logic
    single_unit = Unit.objects.get(slug=slug)
    comments = Comments.objects.filter(unit=single_unit)

    if request.method == 'POST':
        commentform = CommentForm(request.POST)
        if commentform.is_valid():
            myform = commentform.save(commit=False)
            myform.author = request.user
            myform.post = single_unit
            myform.save()
    
    else:
        commentform = CommentForm()

    return render(request,'units/single_unit.html',{'unit':single_unit,  'comments':comments, 'commentform':commentform })


def new_unit(request):
    #print('In View')
    if request.method=='POST':  # new post to the blog
        form = UnitForm(request.POST or None , request.FILES or None)
        if form.is_valid():
            form.save()
            return redirect(reverse('units:all_units_list'))

    else:  # show form 
        form = UnitForm()
    return render(request,'units/new.html',{'form':form})



def unit_edit(request,slug):
    single_unit = Unit.objects.get(slug=slug)
    if request.method=='POST':  # new post to the blog
        form = UnitForm(request.POST or None , request.FILES or None , instance=single_unit)
        if form.is_valid():
            form.save()
            return redirect(reverse('units:all_units_list'))

    else:  # show form 
        form = UnitForm(instance=single_unit)
    return render(request,'units/new.html',{'form':form})


def unit_delete(request, slug):
    obj = get_object_or_404(Unit, slug=slug)
    template_name = 'units/delete.html'
    if request.method == "POST":
        obj.delete()
        return redirect("/units")
    context = {"object": obj}
    return render(request, template_name, context)  



class unit_list(ListView):
    model = Unit



class unit_detail(DetailView):
    model = Unit


class unit_update(UpdateView):
    model = Unit
    fields = ['title','price']
    success_url = '/unit/cbv'

units/templates/units/all_units.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>AIRBNB Clone Fahd Mannaa</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        <div class='row'>

            <h1> <a href="{% url 'units:all_units_list' %}">Weclome To Our Blog </a> </h1>
            <br>
            <h2><a href="{% url 'units:new_unit' %}"> Add New Unit</a></h2>
            <hr>
            {% for object in units %}
               <h3><a href="{{object.get_absolute_url}}">{{object}}</a> </h3>
            {% endfor %}
        </div>
        
        <script src="" async defer></script>
    </body>
</html>

units/templates/units/delete.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Are you sure you want to delete the following:</h1>
        <p> {{ object.title }}</p>
        
        <form method='POST' >{% csrf_token %}
        
            <button class='btn btn-danger'>Yes, delete</button>
        
        </form>
        
        <script src="" async defer></script>
    </body>
</html>

units/templates/units/new.html
<h1> <a href="{% url 'units:all_units_list' %}">Weclome AIRBNB </a> </h1>
<h2>Add New Unit</h2>
<hr>


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit"  value="new post">
</form>

units/templates/units/single_unit.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        
            {{unit}}

            {{unit.description}}
            {{unit.price}}



            <h3>{{unit.created}}</h3>


            <img src="{{unit.image.url}}" alt="">
<br>
            <h3> Comments </h3>

            {% for comment in comments %}
                <h5>{{comment.text}}</h5>
                <h5>{{comment.author}}</h5>
            {% endfor %}

            <h3> Or Leave Your Comment</h3>
            <form method="POST">
                {% csrf_token %}
                {{commentform}}
                <input type="submit" value="Add Comment">
            </form>
        
        <script src="" async defer></script>
    </body>
</html>

units/templates/units/unit_detail.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        
            {{unit}}

            {{unit.description}}
            {{unit.price}}



            <h3>{{unit.created}}</h3>


            <img src="{{unit.image.url}}" alt="">
        
        <script src="" async defer></script>
    </body>
</html>

units/templates/units/unit_form.html
<h1> <a href="{% url 'units:all_units_list' %}">Weclome AIRBNB </a> </h1>
<h2>Add New Unit</h2>
<hr>


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit"  value="new post">
</form>

units/templates/units/unit_list.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>AIRBNB Clone Fahd Mannaa</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        <div class='row'>

            <h1> <a href="{% url 'units:all_units_list' %}">Weclome To Our Blog </a> </h1>
            <br>
            <h2><a href="{% url 'units:new_unit' %}"> Add New Unit</a></h2>
            <hr>
            {% for object in object_list %}
               <h3><a href="{{object.get_absolute_url}}">{{object}}</a> </h3>
            {% endfor %}
        </div>
        
        <script src="" async defer></script>
    </body>
</html>